FP-137 Fluidplayer_(GitHub_556)_Play main video after preRoll ends not work
fluid-player/fluid-player pull request #670
Opened 2022-07-18 16:31 UTC by ZentoDH

2022-07-18 16:43 UTC, fpfcarvalho approved these changes

2022-07-18 16:45 UTC, leroybm requested changes

2022-07-18 16:45 UTC, leroybm commented on src/modules/vpaid.js
> +        if(!playerInstance.vpaidAdUnit) {
```suggestion
        if (!playerInstance.vpaidAdUnit) {
```

2022-07-18 16:45 UTC, leroybm commented on src/modules/vpaid.js
> +            return
```suggestion
            return;
```

2022-07-19 09:13 UTC, leroybm approved these changes

2022-09-26 11:28 UTC, merged