FP-186 Support Video Waterfall VAST Response
fluid-player/fluid-player pull request #714
Opened 2023-03-01 19:01 UTC by leroybm

2023-03-07 13:28 UTC, MariaAlmeidaMJ approved these changes

2023-03-07 16:06 UTC, fpfcarvalho requested changes

2023-03-07 16:06 UTC, fpfcarvalho commented on test/static/vast_ad_buffet.xml
> +            <Impression id="exotr"><![CDATA[https://syndication.realsrv.com/vregister.php?a=vimp&tracking_event=impression&idzone=4890178&2f619b13242072d9159f66efe8cd218d=tsVuZ8uHLnt4ctvDtq48PXLz64ct
this shouldn't have the "https://syndication.realsrv.com/vregister.php?". should be something dummy here

2023-03-07 16:06 UTC, fpfcarvalho commented on test/static/vast_ad_buffet_with_error.xml
> +            <Impression id="exotr"><![CDATA[https://syndication.realsrv.com/vregister.php?a=vimp&tracking_event=impression&idzone=4890178&2f619b13242072d9159f66efe8cd218d=tsVuZ8uHLnt4ctvDtq48PXLz64ct
this shouldn't have the "https://syndication.realsrv.com/vregister.php?". should be something dummy here

2023-03-07 16:06 UTC, fpfcarvalho commented on test/static/vast_ad_pod.xml
> +            <Impression id="exotr"><![CDATA[https://syndication.realsrv.com/vregister.php?a=vimp&tracking_event=impression&idzone=4890178&2f619b13242072d9159f66efe8cd218d=tsVuZ8uHLnt4ctvDtq48PXLz64ct
this shouldn't have the "https://syndication.realsrv.com/vregister.php?". should be something dummy here

2023-03-07 16:06 UTC, fpfcarvalho commented on test/static/vast_wrapper_fallbackOnNoAd_false.xml
> +            <Impression id="exotr"><![CDATA[https://syndication.realsrv.com/vregister.php?a=vimp&tracking_event=impression&idzone=4890178&2f619b13242072d9159f66efe8cd218d=tsVuZ8uHLnt4ctvDtq48PXLz64ct
this shouldn't have the "https://syndication.realsrv.com/vregister.php?". should be something dummy here

2023-03-07 16:06 UTC, fpfcarvalho commented on test/static/vast_wrapper_fallbackOnNoAd_true.xml
> +            <Impression id="exotr"><![CDATA[https://syndication.realsrv.com/vregister.php?a=vimp&tracking_event=impression&idzone=4890178&2f619b13242072d9159f66efe8cd218d=tsVuZ8uHLnt4ctvDtq48PXLz64ct
this shouldn't have the "https://syndication.realsrv.com/vregister.php?". should be something dummy here

2023-03-08 09:20 UTC, fpfcarvalho approved these changes

2023-03-09 16:38 UTC, merged

2023-03-16 04:47 UTC, golfnoii commented
InfernalGunner99:dependabot/npm_and_yarn/json5-2.2.3

2023-03-18 04:58 UTC, yyyyuuuuu commented
CHANGELOG.md

2023-03-25 22:58 UTC, InfernalGunner99 reviewed
Approval

2023-03-25 23:07 UTC, InfernalGunner99 reviewed
Ag

2023-04-06 06:17 UTC, InfernalGunner99 reviewed
T

2023-04-22 19:45 UTC, InfernalGunner99 reviewed
R