FP-259 Create E2E project for Fluid Player
fluid-player/fluid-player pull request #859
Opened 2024-12-02 16:53 UTC by ZentoDH

2024-12-03 08:01 UTC, MariaAlmeidaMJ approved these changes

2024-12-04 00:02 UTC, EdyNakal1991 commented
Pada Sel, 3 Dis 2024 16:02 MariaAlmeidaMJ ***@***.***>
menulis:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fluid-player/fluid-player/pull/859#pullrequestreview-2474847051>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARQKWTL2ZQLJFBHTYLFU6WL2DVQQRAVCNFSM6AAAAABS33RVNKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDINZUHA2DOMBVGE>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-12-04 10:07 UTC, fpfcarvalho requested changes

2024-12-04 10:07 UTC, fpfcarvalho commented on e2e/functions/video.ts
> +// }
can we remove this?

2024-12-04 10:07 UTC, fpfcarvalho commented on playwright.config.ts
> +// dotenv.config({ path: path.resolve(__dirname, '.env') });
can we remove this?

2024-12-04 11:21 UTC, fpfcarvalho approved these changes

2024-12-04 13:50 UTC, MariaAlmeidaMJ approved these changes

2024-12-09 14:24 UTC, merged